// Feste Liste aller 66 biblischen Bücher, kanonische Reihenfolge.
//
// Wird als options.list im sermon-Schema verwendet, damit `book` niemals ein
// Freitextfeld ist. Freitext zerstört die Filterbarkeit dauerhaft
// ("Röm 8" / "Römer 8,1" / "Rom. 8" wären drei verschiedene Werte).
//
// `value` ist ein stabiler ASCII-Key, der sich auch bei Rechtschreibkorrekturen
// am `title` nicht ändert. `title` ist der Anzeigename.
export const bibleBooks = [
  // Altes Testament
  { value: '1-mose', title: '1. Mose' },
  { value: '2-mose', title: '2. Mose' },
  { value: '3-mose', title: '3. Mose' },
  { value: '4-mose', title: '4. Mose' },
  { value: '5-mose', title: '5. Mose' },
  { value: 'josua', title: 'Josua' },
  { value: 'richter', title: 'Richter' },
  { value: 'rut', title: 'Rut' },
  { value: '1-samuel', title: '1. Samuel' },
  { value: '2-samuel', title: '2. Samuel' },
  { value: '1-koenige', title: '1. Könige' },
  { value: '2-koenige', title: '2. Könige' },
  { value: '1-chronik', title: '1. Chronik' },
  { value: '2-chronik', title: '2. Chronik' },
  { value: 'esra', title: 'Esra' },
  { value: 'nehemia', title: 'Nehemia' },
  { value: 'ester', title: 'Ester' },
  { value: 'hiob', title: 'Hiob' },
  { value: 'psalm', title: 'Psalm' },
  { value: 'sprueche', title: 'Sprüche' },
  { value: 'prediger', title: 'Prediger' },
  { value: 'hoheslied', title: 'Hoheslied' },
  { value: 'jesaja', title: 'Jesaja' },
  { value: 'jeremia', title: 'Jeremia' },
  { value: 'klagelieder', title: 'Klagelieder' },
  { value: 'hesekiel', title: 'Hesekiel' },
  { value: 'daniel', title: 'Daniel' },
  { value: 'hosea', title: 'Hosea' },
  { value: 'joel', title: 'Joel' },
  { value: 'amos', title: 'Amos' },
  { value: 'obadja', title: 'Obadja' },
  { value: 'jona', title: 'Jona' },
  { value: 'micha', title: 'Micha' },
  { value: 'nahum', title: 'Nahum' },
  { value: 'habakuk', title: 'Habakuk' },
  { value: 'zefanja', title: 'Zefanja' },
  { value: 'haggai', title: 'Haggai' },
  { value: 'sacharja', title: 'Sacharja' },
  { value: 'maleachi', title: 'Maleachi' },
  // Neues Testament
  { value: 'matthaeus', title: 'Matthäus' },
  { value: 'markus', title: 'Markus' },
  { value: 'lukas', title: 'Lukas' },
  { value: 'johannes', title: 'Johannes' },
  { value: 'apostelgeschichte', title: 'Apostelgeschichte' },
  { value: 'roemer', title: 'Römer' },
  { value: '1-korinther', title: '1. Korinther' },
  { value: '2-korinther', title: '2. Korinther' },
  { value: 'galater', title: 'Galater' },
  { value: 'epheser', title: 'Epheser' },
  { value: 'philipper', title: 'Philipper' },
  { value: 'kolosser', title: 'Kolosser' },
  { value: '1-thessalonicher', title: '1. Thessalonicher' },
  { value: '2-thessalonicher', title: '2. Thessalonicher' },
  { value: '1-timotheus', title: '1. Timotheus' },
  { value: '2-timotheus', title: '2. Timotheus' },
  { value: 'titus', title: 'Titus' },
  { value: 'philemon', title: 'Philemon' },
  { value: 'hebraeer', title: 'Hebräer' },
  { value: 'jakobus', title: 'Jakobus' },
  { value: '1-petrus', title: '1. Petrus' },
  { value: '2-petrus', title: '2. Petrus' },
  { value: '1-johannes', title: '1. Johannes' },
  { value: '2-johannes', title: '2. Johannes' },
  { value: '3-johannes', title: '3. Johannes' },
  { value: 'judas', title: 'Judas' },
  { value: 'offenbarung', title: 'Offenbarung' },
] as const;
